services:
  api:
    build:
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - conf/.env
    depends_on:
      - kinoratedb

  kinoratedb:
    image: postgres:16
    container_name: kinoratedb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=kinorate
      - POSTGRES_DB=kinorate_db
      - POSTGRES_PASSWORD=kk9asdk1j23
      - PGDATA=/var/lib/postgresql/data/pgdata

volumes:
  postgres_data:
