[project]
name = "kinorate"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp[speedups]>=3.13.1",
    "alembic>=1.16.1",
    "asyncpg>=0.30.0",
    "authx>=1.4.3",
    "bcrypt>=5.0.0",
    "cryptography>=46.0.2",
    "fastapi>=0.115.12",
    "pydantic-settings>=2.9.1",
    "python-multipart>=0.0.20",
    "ruff>=0.14.2",
    "slowapi>=0.1.9",
    "sqlalchemy>=2.0.41",
    "uuid-utils>=0.11.0",
    "uvicorn>=0.34.2",
]

[tool.ruff]
line-length = 127
indent-width = 4
include = ["app"]

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
    "C4",  # flake8-comprehensions
    "UP",  # pyupgrade
]
ignore = [
    "E501",  # line too long, handled by black
    "B008",  # do not perform function calls in argument defaults
    "C901",  # too complex
    "W191",  # indentation contains tabs
]

[tool.uv.workspace]
members = ["venv"]
