"""add index to tmdb_id in movies table

Revision ID: 26ab312e1f86
Revises: 5cdef010cca9
Create Date: 2025-10-29 12:48:16.002762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26ab312e1f86'
down_revision: Union[str, None] = '5cdef010cca9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('movies_tmdb_id_key'), 'movies', type_='unique')
    op.create_index(op.f('ix_movies_tmdb_id'), 'movies', ['tmdb_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movies_tmdb_id'), table_name='movies')
    op.create_unique_constraint(op.f('movies_tmdb_id_key'), 'movies', ['tmdb_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
