"""foreign keys fix

Revision ID: 4e756e8b8d0c
Revises: c311e9dcf578
Create Date: 2025-10-24 19:52:45.887508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e756e8b8d0c'
down_revision: Union[str, None] = 'c311e9dcf578'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recentions', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('recentions', sa.Column('movie_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'recentions', 'movies', ['movie_id'], ['id'])
    op.create_foreign_key(None, 'recentions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recentions', type_='foreignkey')
    op.drop_constraint(None, 'recentions', type_='foreignkey')
    op.drop_column('recentions', 'movie_id')
    op.drop_column('recentions', 'user_id')
    # ### end Alembic commands ###
