"""add poster path to movie

Revision ID: 5cdef010cca9
Revises: bd7515a80a87
Create Date: 2025-10-29 00:39:31.561337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cdef010cca9'
down_revision: Union[str, None] = 'bd7515a80a87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('poster_path', sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'poster_path')
    # ### end Alembic commands ###
