"""cascade

Revision ID: 60619817b4f7
Revises: 26ab312e1f86
Create Date: 2025-10-29 15:05:09.479638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60619817b4f7'
down_revision: Union[str, None] = '26ab312e1f86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('recentions_user_id_fkey'), 'recentions', type_='foreignkey')
    op.drop_constraint(op.f('recentions_movie_id_fkey'), 'recentions', type_='foreignkey')
    op.create_foreign_key(None, 'recentions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'recentions', 'movies', ['movie_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recentions', type_='foreignkey')
    op.drop_constraint(None, 'recentions', type_='foreignkey')
    op.create_foreign_key(op.f('recentions_movie_id_fkey'), 'recentions', 'movies', ['movie_id'], ['id'])
    op.create_foreign_key(op.f('recentions_user_id_fkey'), 'recentions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
